linkedin_data_stub = {
    "public_identifier": "vidyut-latay",
    "first_name": "Vidyut",
    "last_name": "Latay",
    "full_name": "Vidyut Latay",
    "occupation": "UX Tutor at CareerFoundry",
    "headline": "UX Designer and Documentary Filmmaker",
    "summary": "UX Researcher and Designer with a background in documentary filmmaking. Years of experience in research and storytelling. Empathy, curiosity, and problem solving define me.  I look forward to blending in my unique experience of the audio-visual medium with the design world; build products and services that offer a smooth, appealing, and easy user experience.\n\nhttps://vidyut-latay.squarespace.com/\n\nI am also currently producing and directing a feature documentary about legal, high-skilled immigrants in the US.\n\nhttp://www.vidyutlatay.com/",
    "country": "US",
    "country_full_name": "United States",
    "state": "New Canaan",
    "experiences": [
        {
            "starts_at": {"day": 1, "month": 6, "year": 2017},
            "ends_at": None,
            "company": "Vidyut Latay Productions",
            "company_linkedin_profile_url": None,
            "title": 'Producer/Director/Editor: Documentary "ALIEN:The Story of America\'s legal, high-skilled immigrants."',
            "description": "• Directing/Producing and Editing a feature documentary about the plight of legal, high-skilled immigrants in the United States.• The film intends to spread awareness and create positive changes in immigration policiesconcerning high-skilled immigrants.http://www.vidyutlatay.com/alien/directors_note",
            "location": "Greater New York City Area",
            "logo_url": None,
        },
        {
            "starts_at": {"day": 1, "month": 1, "year": 2020},
            "ends_at": {"day": 1, "month": 6, "year": 2020},
            "company": "App: Amplio; SAAS app (https://amplio.ai/)",
            "company_linkedin_profile_url": None,
            "title": "UX Consultant",
            "description": "Part of a team of four UX designers designing a dashboard for the SAAS application system that helps coaches build better teams.• Competitive Analysis• User Research and Interviews with coaches.• Journeys, User Flows, Wireframes, and Prototyping.• Usability testing",
            "location": "New York, New York, United States",
            "logo_url": None,
        },
        {
            "starts_at": {"day": 1, "month": 6, "year": 2019},
            "ends_at": {"day": 1, "month": 12, "year": 2019},
            "company": "Film Nonprofit: Filmmakers Alliance",
            "company_linkedin_profile_url": None,
            "title": "UX Researcher and Designer: App: FA",
            "description": "•\tConceived, researched, developed and designed one of the first filmmaking apps that will help independent filmmakers across the United States.•\tConducted competitive analysis of film non-profit websites, User interviews with FA members.•\tBuilt User personas, Task Analysis, User Flows, and Site Map.•\tDesigned Wire-frames, Low-fidelity and High-fidelity prototype.",
            "location": "Greater New York City Area",
            "logo_url": None,
        },
        {
            "starts_at": {"day": 1, "month": 4, "year": 2019},
            "ends_at": {"day": 1, "month": 8, "year": 2019},
            "company": "App: Fit Me",
            "company_linkedin_profile_url": None,
            "title": "UX Researcher and Designer",
            "description": "• Conceived and designed a health and fitness app, FIT ME, that caters to people with different fitness levels.• Built site map, designed wireframes, low-fidelity, mid-fidelity and high-fidelity prototypes.• Defined and designed for different breakpoints, responsive layouts and grids.• Designed the app logo, created the moodboard, and compiled a style guide.• Created animation for an interaction.",
            "location": "Greater New York City Area",
            "logo_url": None,
        },
        {
            "starts_at": {"day": 1, "month": 10, "year": 2018},
            "ends_at": {"day": 1, "month": 4, "year": 2019},
            "company": "App: Expert",
            "company_linkedin_profile_url": None,
            "title": "UX Researcher and Designer",
            "description": "• Conceived, researched, and designed an app, EXPERT, that is a one stop shop for Expert advice  .• Conducted competitive analysis, user interviews, and user journeys.• Built user personas, task analysis, user flows and site map.• Designed wireframes, low- fidelity, mid-fidelity and high-fidelity prototypes.• Conducted A/B preference testing for the landing page, compiled a style guide.• Designed responsive layouts and grids.",
            "location": "Greater New York City Area",
            "logo_url": None,
        },
        {
            "starts_at": {"day": 1, "month": 1, "year": 2016},
            "ends_at": {"day": 1, "month": 1, "year": 2017},
            "company": "Abbot Documentary Partners and Westside Documentary Partners",
            "company_linkedin_profile_url": None,
            "title": 'Freelance Researcher, Translator: Documentary "Kailash", Produced by Davis Guggenheim',
            "description": "Documentary about Nobel Peace prize winner Kailash Satyarthi and his relentless fight against child slavery and child labor.• Researched the issue of child labor during Development and Pre-production that helpeddevelop the story line of the documentary.• Translated footage shot in India from Hindi to English in the entire post-production stage, singlehandedly edited translations for picture lock for Sundance submission.The documentary won the Grand Jury award at Sundance film festival, 2018.",
            "location": "Los Angeles",
            "logo_url": None,
        },
        {
            "starts_at": {"day": 1, "month": 1, "year": 2008},
            "ends_at": {"day": 1, "month": 1, "year": 2012},
            "company": "Vidyut Latay Productions",
            "company_linkedin_profile_url": None,
            "title": 'Director/Producer, Independent documentary "Beyond Silence" about deaf people in India',
            "description": "• Director/Producer/Editor of the award-winning documentary: ‘Beyond Silence’, based on thelives of deaf people in India. Beyond Silence has screened world- wide and twice on PBS- KVCR.It is one of the first films made in India that celebrates deafness as an alternate way of life.",
            "location": "Greater Los Angeles Area",
            "logo_url": None,
        },
        {
            "starts_at": {"day": 1, "month": 7, "year": 2004},
            "ends_at": {"day": 1, "month": 1, "year": 2006},
            "company": "ZOOM (The Times of India group), Mumbai",
            "company_linkedin_profile_url": None,
            "title": "Executive Producer",
            "description": "• In charge of the highly successful show ‘Page 3’, the first of its kind in India, inspired from E!Entertainment. The show exhibited the lives of the rich, famous and socialites in India.• At Zoom, Vidyut even worked in the capacity of a show director and reporter for film-based shows where she interviewed India’s top Bollywood directors, producers and actors.",
            "location": None,
            "logo_url": None,
        },
        {
            "starts_at": {"day": 1, "month": 7, "year": 2002},
            "ends_at": {"day": 1, "month": 7, "year": 2004},
            "company": "Zee Network, Mumbai",
            "company_linkedin_profile_url": None,
            "title": "Executive Producer",
            "description": "Creatively supervised the programs - supervised the scripts, edits, styling and the overall look and the feel of the shows.•Kept a track of the market-wise and target-wise performance of the programs, and took corrective actions in the programs and the promotions accordingly.•Evaluated new proposals and gave creative inputs on upcoming proposals, till the program was commissioned and handed over to one of the executive producers.•Initiated various program innovations with the Sales and Client servicing Department•Handled the telecast of the Public service messages under the Zee Touch India initiatives",
            "location": None,
            "logo_url": None,
        },
        {
            "starts_at": {"day": 1, "month": 4, "year": 2002},
            "ends_at": {"day": 1, "month": 7, "year": 2002},
            "company": "Zee Education, Mumbai",
            "company_linkedin_profile_url": None,
            "title": "Content developer",
            "description": None,
            "location": None,
            "logo_url": None,
        },
        {
            "starts_at": {"day": 1, "month": 8, "year": 2020},
            "ends_at": None,
            "company": "CareerFoundry",
            "company_linkedin_profile_url": "https://www.linkedin.com/company/careerfoundry",
            "title": "UX Tutor",
            "description": "-Evaluating student submissions, providing regular detailed feedback, suggestions, and additional reading material references to improve the quality of student submissions- Working closely with mentors to provide guidance to students on creating an industry-ready portfolio of project works and making them ready to get hired.- Working closely with the curriculum and mentor team in suggesting learning materials and strategies for helping students transitioning to UX Design from diverse backgrounds.",
            "location": "Remote",
            "logo_url": None,
        },
        {
            "starts_at": {"day": 1, "month": 1, "year": 2014},
            "ends_at": {"day": 1, "month": 8, "year": 2016},
            "company": "From the Heart Productions, Inc.",
            "company_linkedin_profile_url": "https://www.linkedin.com/company/from-the-heart-productions-inc.",
            "title": "Strategic Partnership Liaison",
            "description": "• Marketed and promoted for the Roy W. Dean film-grant and Intentional filmmakingmentoring classes that consistently increased the submissions every grant cycle.• Built strategic partnerships with film & media companies that offered discounted servicesranging from 20% to 80%, In-kind donations, personal consultations and cash donations.",
            "location": "Greater Los Angeles Area",
            "logo_url": None,
        },
        {
            "starts_at": {"day": 1, "month": 5, "year": 2010},
            "ends_at": {"day": 1, "month": 8, "year": 2015},
            "company": "Filmmakers Alliance",
            "company_linkedin_profile_url": "https://www.linkedin.com/company/filmmakers-alliance",
            "title": "Executive Director",
            "description": "• Kept all organization programs current and satisfied the needs of the diverse membership,including relationship with global filmmaking societies, i.e.“Bollywood”.• Coordinated the Fiscal sponsorship film granting program and equipment rentals.• Point person contact for membership.• Coordinated the content management of the website.• Day-to-Day office administration, scheduled meetings, master classes,  organized screenings,programmed films for Vision Fest and Echo Park Film center screenings.",
            "location": "Greater Los Angeles Area",
            "logo_url": None,
        },
        {
            "starts_at": {"day": 1, "month": 4, "year": 2014},
            "ends_at": {"day": 1, "month": 7, "year": 2014},
            "company": "Downtown Film Festival Los Angeles",
            "company_linkedin_profile_url": "https://www.linkedin.com/company/downtown-film-festival-los-angeles",
            "title": "Programmer",
            "description": "• Judged Short films, documentaries and features and moderated live post film discussion at LA  Live, for the Downtown film festival, Los Angeles, 2014.",
            "location": "Los Angeles",
            "logo_url": None,
        },
    ],
    "education": [
        {
            "starts_at": {"day": 1, "month": 1, "year": 2019},
            "ends_at": {"day": 1, "month": 1, "year": 2019},
            "field_of_study": "Human-Centered Design",
            "degree_name": "Introduction to Human Centred Design",
            "school": "+Acumen and IDEO",
            "school_linkedin_profile_url": None,
            "description": "Intensive, hands-on, online learning experience about developing human-centered solutions that can help reduce poverty, bias against employing handicapped people and create positive impact in marginalized communities around the world.Developed a prototype for training and educating corporations for employing handicapped people.",
            "logo_url": None,
            "grade": None,
            "activities_and_societies": None,
        },
        {
            "starts_at": {"day": 1, "month": 1, "year": 2018},
            "ends_at": {"day": 1, "month": 1, "year": 2019},
            "field_of_study": "UX/UI Design",
            "degree_name": "Certified UX Designer with a specialization in UI",
            "school": "Career Foundry",
            "school_linkedin_profile_url": None,
            "description": "Studied UX Designing and specialized in UI Designing in a Boot Camp style coaching from Career Foundry.Mentored by industry professionals for 12 months.Designed two apps under the guidance of industry mentors.",
            "logo_url": None,
            "grade": None,
            "activities_and_societies": None,
        },
        {
            "starts_at": {"day": 1, "month": 1, "year": 2007},
            "ends_at": {"day": 1, "month": 1, "year": 2008},
            "field_of_study": "Radio and Television",
            "degree_name": "M.A",
            "school": "San Francisco State University, San Francisco, CA",
            "school_linkedin_profile_url": None,
            "description": None,
            "logo_url": None,
            "grade": None,
            "activities_and_societies": None,
        },
        {
            "starts_at": {"day": 1, "month": 1, "year": 1999},
            "ends_at": {"day": 1, "month": 1, "year": 2001},
            "field_of_study": "Mass Communication, Video Production",
            "degree_name": "Masters in Communication Studies",
            "school": "Savitribai Phule Pune University, Pune, India",
            "school_linkedin_profile_url": None,
            "description": None,
            "logo_url": None,
            "grade": None,
            "activities_and_societies": None,
        },
        {
            "starts_at": {"day": 1, "month": 1, "year": 1997},
            "ends_at": {"day": 1, "month": 1, "year": 1999},
            "field_of_study": "Statistics",
            "degree_name": "Masters in Science",
            "school": "Maharaja Sayajirao University of Baroda, Vadodara, India",
            "school_linkedin_profile_url": None,
            "description": None,
            "logo_url": None,
            "grade": None,
            "activities_and_societies": None,
        },
    ],
    "accomplishment_honors_awards": [
        {
            "title": "Winner- First Runner up/2nd prize at Shorts Showcase Festival, PBS",
            "issuer": "Shorts Showcase program on PBS",
            "issued_on": {"day": 1, "month": 10, "year": 2014},
            "description": "Shorts showcase Festival, PBS-KVCR, USA, 2014",
        },
        {
            "title": "Audience Choice Award winner --Beyond Silence",
            "issuer": "Mumbai Women's International Film Festival, Mumbai, India, 2013",
            "issued_on": {"day": 1, "month": 10, "year": 2013},
            "description": None,
        },
        {
            "title": "Best shorts award of merit",
            "issuer": "Best shorts competition, La Jolla, California",
            "issued_on": {"day": 1, "month": 10, "year": 2012},
            "description": "Winner of Best Shorts award for short documentary",
        },
    ],
    "accomplishment_projects": [
        {
            "starts_at": None,
            "ends_at": None,
            "title": "Beyond Silence ( Documentary based on the lives of deaf people in India)",
            "description": "Guest Speaker at the Mass Media class, UCLA, May, 2015Screening at the CLINTON THEATER, Portland, January, 2015PBS Shorts showcase screening, November 2014Winner, 1st Runner up- Second Prize at the Shorts showcase film festival, October 2014, PBS-KVCR.UCLA Mass Media class, May 2014Mumbai Women's International Film Festival, Mumbai, October 2013Cinedeaf-Rome International deaf film festival, 2013.PBS Shorts showcase screening, August 2013Downtown Film Festival, Los Angeles, July 2013Italian Film Festival, Bologna, Italy, June 2013Whitechapel Library, East London, May 2013UCLA, Los Angeles, May 2013Roopkar Film Festival, Guwahati, India, April 2013Incloodu, London (First Film Festival celebrating deaf culture), November 20130110 International Digital Film Festival, Mumbai, 2013Cannes Film Festival - Short Film Corner, France 2012Cyprus International Film Festival, Cyprus 2012Peloponnesian Corinthian International Film Festival Greece 2012, Greece 2012Award of Merit for Short Documentary - Best Shorts Competition, LA Jolla CA 2012VisionFest, Downtown Independent Theatre, Los AngelesEcho Park Film Center, Los Angeles",
            "url": "http://www.youtube.com/watch?v=oNwFLeEJXKU",
        }
    ],
    "connections": 500,
    "recommendations": [
        "Vidyut did a great job collecting user inputs for us and developing a UI/UX experience that has garner us praise from our clients. She made the interface not only usable but incredibly intuitive. She is a great person to work with and try’s to always put our needs first. Could not recommend her more.",
        "Vidyut will make a great UX Researcher for any company that hires her. Although at the time of this posting she is new to this profession her ability to learn, work ethic, and extensive background in producing documentaries gives her a unique skill set you just can't find in the most senior UX researcher. \n\nI'm confident she will help you uncover and analyze the needs of your customers and be an invaluable asset to your company.",
    ],
    "similarly_named_profiles": [
        {
            "name": "Vidyut Latay",
            "link": "https://www.linkedin.com/in/vidyut-latay-2445532",
            "summary": "-",
            "location": "Santa Clara, CA",
        }
    ],
}
